ARG AIRFLOW_IMAGE_NAME=apache/airflow:3.3.0-python3.13
FROM ${AIRFLOW_IMAGE_NAME}

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        openjdk-17-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements-airflow.txt /requirements-airflow.txt

RUN pip install \
    --no-cache-dir \
    -r /requirements-airflow.txt